#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets



class doipass(object):
    def setupUi(self, Main):
        Main.setObjectName("MainWindow")
        Main.resize(713, 379)
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_Username_chagne = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Username_chagne.setGeometry(QtCore.QRect(280, 20, 361, 31))
        self.lineEdit_Username_chagne.setObjectName("lineEdit_Username_chagne")
        self.lineEdit_pass_chagne = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_pass_chagne.setGeometry(QtCore.QRect(280, 80, 361, 31))
        self.lineEdit_pass_chagne.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass_chagne.setObjectName("lineEdit_pass_chagne")
        self.lineEdit_Username_new = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Username_new.setGeometry(QtCore.QRect(280, 140, 361, 31))
        self.lineEdit_Username_new.setObjectName("lineEdit_Username_new")
        self.lineEdit_pass_new = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_pass_new.setGeometry(QtCore.QRect(280, 200, 361, 31))
        self.lineEdit_pass_new.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass_new.setObjectName("lineEdit_pass_new")
        self.lineEdit_confirm_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_confirm_pass.setGeometry(QtCore.QRect(280, 260, 361, 31))
        self.lineEdit_confirm_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_confirm_pass.setObjectName("lineEdit_confirm_pass")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText("Tên Đăng Nhập:")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setText("Nhập Mật Khẩu Cũ:")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setText("Nhập Tên Mới:")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setText("Nhập Mật Khẩu Mới:")
        self.btn_Thoat_chagne = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Thoat_chagne.setGeometry(QtCore.QRect(280, 320, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_Thoat_chagne.setFont(font)
        self.btn_Thoat_chagne.setObjectName("btn_Thoat_chagne")
        self.btn_XN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_XN.setGeometry(QtCore.QRect(460, 320, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_XN.setFont(font)
        self.btn_XN.setObjectName("btn_XN")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Thoat_chagne.setText(_translate("MainWindow", "Thoát"))
        self.btn_XN.setText(_translate("MainWindow", "Xác Nhận"))







