#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector


class dbMng():
    def __init__(self, dbname='qlks'):
        self.dbname = dbname
        self.conn = None
        self.cur = None
        self.open_connect()

    def open_connect(self):
        self.conn = mysql.connector.connect(host="localhost", user="root", password="", database=self.dbname)
        self.cur = self.conn.cursor()

    def close_connect(self):
        if self.conn is not None:
            self.conn.close()



